"""Initial migrate

Revision ID: 888885d19762
Revises: 3c2fb44cfa2a
Create Date: 2024-07-10 11:54:53.180715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888885d19762'
down_revision = '3c2fb44cfa2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('earthquakes', 'magnitude',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('earthquakes', 'magnitude',
               existing_type=sa.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
